spring:
  datasource:
    url: jdbc:mysql://localhost:3310/trendlog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: trendlog
    password: trendlog
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
